### ISSUE TITLE
HiDPI support in Slicers

### ISSUE THREAD

**Issue by cheinzl** [3dct/open_iA#10]
HiDPI support to be added in Slicers 

Currently the position of the observer (retrieving data values below the mouse cursor) is not shown at the right position. Potentially a scaling factor needs to be integrated

**Comment by codeling** [comment]
Issue only observed under Mac OS so far.

**Comment by codeling** [comment]
Does not happen anymore on current mac os X (14) - tested with VTK 9.2.6, Qt 6.6.0.
