### ISSUE TITLE
[JOSS REVIEW] Statement of need 

### ISSUE THREAD

**Issue by trallard** [3dct/open_iA#31]
The paper includes a very brief statement of what the package does:

> The main driver behind its development is to provide a common framework for performing visual analytics on industrial Computed Tomography (CT) data

but there is no explicit statement of need (i.e. what problem does the package solves or what does this offer that others do not)

**Comment by trallard** [comment]
Related to [https://github.com/openjournals/joss-reviews/issues/1185](https://github.com/openjournals/joss-reviews/issues/1185)

**Comment by codeling** [comment]
We have added the following sentences:

> In contrast to general volume visualization or processing software, it offers specialized tools, which address domain-specific analysis scenarios such as porosity determination, fiber characterization and image processing parameter space analysis. The wide range of building blocks, which these tools consist of, facilitate the development of new research prototypes in this application domain.

We hope that with this we could address your concern?

**Comment by katyhuff** [comment]
@trallard  I just wanted to bump this, as the review is growing a bit stale. Thoughts?

**Comment by trallard** [comment]
Yes this is more than enough closing now
