### ISSUE TITLE
[JOSS REVIEW] Install instructions

### ISSUE THREAD

**Issue by trallard** [3dct/open_iA#32]
Related to [https://github.com/openjournals/joss-reviews/issues/1185](https://github.com/openjournals/joss-reviews/issues/1185)

There are detailed instructions for development installs, but there are no instructions for the general usage (i.e. I want to use the tool but not necessarily add a new function).

It might be worth to:
- Package the latest release in a way that could be relatively easily installed by both Windows and unix users
- Provide the instructions on the wiki in addition to the development ones

**Comment by codeling** [comment]
Thanks for the feedback!

- We try to provide installable binaries for testing/using our software through the [open_iA releases](https://github.com/3dct/open_iA/releases) page; we currently provide binaries for Windows (7-10) as well as Linux. The linux build should work at least on current Ubuntu and derivatives; we unfortunately don't know an easy mechanism at the moment for providing binaries that work across multiple linux/unix distributions, and we don't have the resources to run builds for multiple distributions. If you have any proposals how we could improve that situation we'd be very glad! We have started looking into the flatpak format, and might provide such packages in the near future, but so far we couldn't get our program to reliably run within its sandboxing mechanisms, the major issue was with access to files.

- As for instructions, our Readme.md references the releases page ("For trying it out, download the latest binary version from github."), as well as the wiki front page (section "Getting open_iA"). Do you have any suggestions how we can make this information more accessible? I have reformulated the release text in the hopes that this clears things up a bit already.

**Comment by katyhuff** [comment]
@trallard : have you checked out the binaries mentioned above? The linux binary works for me, as does the superbuild. (but I'm not on windows...)

**Comment by trallard** [comment]
Fab. All works as expected, I might have just missed this bits
