### ISSUE TITLE
Stack export 0 ist immer die Preview

### ISSUE THREAD

**Issue by mdalpiaz** [3dct/open_iA#72]
Wenn man einen Stack an Slices exportieren will, ist Bild 0 immer das, was zu Beginn in der Preview angezeigt wird. Bild 1 ist wieder richtig.

**Comment by codeling** [comment]
Fixed with https://github.com/3dct/open_iA/commit/4ad3ce9b38b003cb7db326d50d23e9a7cc3f9313
