### ISSUE TITLE
add indicators for slice number in slice view

### ISSUE THREAD

**Issue by lukasbehammer** [3dct/open_iA#76]
Add option to show indicators for the slice number in the slice view like in the following image:
![image](https://github.com/user-attachments/assets/7adba6e8-360f-455c-b6c5-b42e80f0a8de)

**Comment by codeling** [comment]
A rudimentary version of this (solid lines, same color as 3D slice plane indicators) is now implemented in develop (see the group of changes with last commit a3789441bc44656fbdcafa748cc48c0fbe6591b3)
